# Configuration file for randomization

save_gifs: False # Save gifs of the simulation
render: False # Display simulation window
num_light_sources: 5 # Number of light sources to add for light_source randomization
render_cam_pos: [-1.5, -1.5, 1.5] # Camera used for gifs
num_episodes: 2 # Number of episodes to generate
dataset_dir_name: "dataset_random_dynamics" # Path to save the dataset

randomization_list: [
    # {'clean'}, 
    # Dynamic parameters
    # {"link_mass"}, 
    # {"joint_damping"}, 
    # {"joint_friction"}, 
    # {"actuator_gain"},
    # {"link_inertia"},
    # {"joint_stiffness"},
    # {'gravity'},
    
    # Vision parameters
    # {"light_source"},
    # {"object_color"},
    # {"robot_color"},
    # {"table_color"},
    # {"real_floor"},
    {"normalize"},
    {"HSV"},
    {"salt_and_pepper"},
    # {"SAM"},
  ]


# random dynamics configs
random_dynamics:
  link_mass: # dynamic parameters
    body.base|inertial.mass: # part_type.part_name|property1.property2.etc
      - [-0.6, 0.6]  # Lower and upper bounds for random noise value (uniformly selected)
      - add  # Operation to apply: add or mul. add will add random noise to the original value, mul will multiply the original value by the random noise
    body.shoulder_link|inertial.mass:
      - [-0.6, 0.6]
      - add
    body.upper_arm_link|inertial.mass:
      - [-0.6, 0.6]
      - add
    body.forearm_link|inertial.mass:
      - [-0.6, 0.6]
      - add
    body.wrist_1_link|inertial.mass:
      - [-0.6, 0.6]
      - add
    body.wrist_2_link|inertial.mass:
      - [-0.6, 0.6]
      - add
    body.wrist_3_link|inertial.mass:
      - [-0.15, 0.15]
      - add

  joint_damping:
    joint.shoulder_pan_joint|damping:
      - [0, 2.99]
      - add
    joint.shoulder_lift_joint|damping:
      - [0, 2.99]
      - add
    joint.elbow_joint|damping:
      - [0, 2.99]
      - add
    joint.wrist_1_joint|damping:
      - [0, 2.99]
      - add
    joint.wrist_2_joint|damping:
      - [0, 2.99]
      - add
    joint.wrist_3_joint|damping:
      - [0, 2.99]
      - add

  joint_friction:
    joint.shoulder_pan_joint|frictionloss:
      - [0, 1]
      - add
    joint.shoulder_lift_joint|frictionloss:
      - [0, 1]
      - add
    joint.elbow_joint|frictionloss:
      - [0, 1]
      - add
    joint.wrist_1_joint|frictionloss:
      - [0, 1]
      - add
    joint.wrist_2_joint|frictionloss:
      - [0, 1]
      - add
    joint.wrist_3_joint|frictionloss:
      - [0, 1]
      - add

  actuator_gain:
    # actuator.shoulder_pan|gainprm:
    actuator.shoulder_pan|kp:
      - [0.5, 2]
      - mul
    # actuator.shoulder_lift|gainprm:
    actuator.shoulder_lift|kp:
      - [0.5, 2]
      - mul
    # actuator.elbow|gainprm:
    actuator.elbow|kp:
      - [0.5, 2]
      - mul
    # actuator.wrist_1|gainprm:
    actuator.wrist_1|kp:
      - [0.5, 2]
      - mul
    # actuator.wrist_2|gainprm:
    actuator.wrist_2|kp:
      - [0.5, 2]
      - mul
    # actuator.wrist_3|gainprm:
    actuator.wrist_3|kp:
      - [0.5, 2]
      - mul

  link_inertia:
    body.base|inertial.diaginertia:
      - [0.5, 1.5]
      - mul
    body.shoulder_link|inertial.diaginertia:
      - [0.5, 1.5]
      - mul
    body.upper_arm_link|inertial.diaginertia:
      - [0.5, 1.5]
      - mul
    body.forearm_link|inertial.diaginertia:
      - [0.5, 1.5]
      - mul
    body.wrist_1_link|inertial.diaginertia:
      - [0.5, 1.5]
      - mul
    body.wrist_2_link|inertial.diaginertia:
      - [0.5, 1.5]
      - mul
    body.wrist_3_link|inertial.diaginertia:
      - [0.5, 1.5]
      - mul

  joint_stiffness:
    joint.shoulder_pan_joint|stiffness:
      - [0, 0.01]
      - add
    joint.shoulder_lift_joint|stiffness:
      - [0, 0.01]
      - add
    joint.elbow_joint|stiffness:
      - [0, 0.01]
      - add
    joint.wrist_1_joint|stiffness:
      - [0, 0.01]
      - add
    joint.wrist_2_joint|stiffness:
      - [0, 0.01]
      - add
    joint.wrist_3_joint|stiffness:
      - [0, 0.01]
      - add

  gravity:
    gravity:
      - [-9.7, -10.1]
      - add

  # Vision parameters
  robot_color:
    material.black|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set
    material.jointgray|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set
    material.linkgray|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set
    material.urblue|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set