# Configuration file for randomization

save_gifs: False
num_light_sources: 5
render_cam_pos: [-1, -2, 3]

randomization_list: [
    {'clean'}, 
    # Dynamic parameters
    {"link_mass"}, 
    {"joint_damping"}, 
    {"joint_friction"}, 
    {"actuator_gain"},
    {"link_inertia"},
    {"joint_stiffness"},
    {'gravity'},
    
    # Vision parameters
    {"light_source"},
    {"object_color"},
    {"robot_color"},
    {"table_color"},
    {"real_floor"},
    # {"HSV"},
    # {"salt_and_pepper"},
    # {"SAM"},
  ]


# random dynamics configs
random_dynamics:
  link_mass: # dynamic parameters
    # Link masses
    body.base|inertial.mass: # part_type.part_name|property1.property2.etc
      - [-0.16106461, -0.16106461]  # Lower and upper bounds for random noise value (uniformly selected)
      - add  # Operation to apply: add or mul. add will add random noise to the original value, mul will multiply the original value by the random noise
    body.shoulder_link|inertial.mass:
      - [-0.26556854, -0.26556854]
      - add
    body.upper_arm_link|inertial.mass:
      - [-0.18818701, -0.18818701]
      - add
    body.forearm_link|inertial.mass:
      - [-0.09126527, -0.09126527]
      - add
    body.wrist_1_link|inertial.mass:
      - [-0.17758173, -0.17758173]
      - add
    body.wrist_2_link|inertial.mass:
      - [-0.13924086, -0.13924086]
      - add
    body.wrist_3_link|inertial.mass:
      - [0.07808112, 0.07808112]
      - add

  joint_damping:
    # Joint damping
    joint.shoulder_pan_joint|damping:
      - [0.03476166, 0.03476166]
      - add
    joint.shoulder_lift_joint|damping:
      - [2.40138833, 2.40138833]
      - add
    joint.elbow_joint|damping:
      - [1.30436714, 1.30436714]
      - add
    joint.wrist_1_joint|damping:
      - [0.39705312, 0.39705312]
      - add
    joint.wrist_2_joint|damping:
      - [0.27984147, 0.27984147]
      - add
    joint.wrist_3_joint|damping:
      - [2.02288293, 2.02288293]
      - add

  joint_friction:
    # Joint friction
    joint.shoulder_pan_joint|frictionloss:
      - [0.54446054, 0.54446054]
      - add
    joint.shoulder_lift_joint|frictionloss:
      - [0.92181085, 0.92181085]
      - add
    joint.elbow_joint|frictionloss:
      - [0.46097485, 0.46097485]
      - add
    joint.wrist_1_joint|frictionloss:
      - [0.04338527, 0.04338527]
      - add
    joint.wrist_2_joint|frictionloss:
      - [0.57062232, 0.57062232]
      - add
    joint.wrist_3_joint|frictionloss:
      - [0.70414167, 0.70414167]
      - add

  actuator_gain:
    # Actuator gain
    actuator.shoulder_pan|gainprm:
      - [578, 578]
      - add
    actuator.shoulder_lift|gainprm:
      - [-897, -897]
      - add
    actuator.elbow|gainprm:
      - [108, 108]
      - add
    actuator.wrist_1|gainprm:
      - [422, 422]
      - add
    actuator.wrist_2|gainprm:
      - [151, 151]
      - add
    actuator.wrist_3|gainprm:
      - [438, 438]
      - add

  link_inertia:
    # Link inertia
    body.base|inertial.diaginertia:
      - [[-0.00149805, -0.00149805, -0.00243292], [-0.00149805, -0.00149805, -0.00243292]]
      - add
    body.shoulder_link|inertial.diaginertia:
      - [[0.00471176, 0.00471176, 0.00305628], [0.00471176, 0.00471176, 0.00305628]]
      - add
    body.upper_arm_link|inertial.diaginertia:
      - [[-0.05434781, -0.05434781, -0.00613249], [-0.05434781, -0.05434781, -0.00613249]]
      - add
    body.forearm_link|inertial.diaginertia:
      - [[0.01004752, 0.01004752, 0.0013196], [0.01004752, 0.01004752, 0.0013196]]
      - add
    body.wrist_1_link|inertial.diaginertia:
      - [[0.0005251, 0.0005251, 0.00045009], [0.0005251, 0.0005251, 0.00045009]]
      - add
    body.wrist_2_link|inertial.diaginertia:
      - [[-0.00112673, -0.00112673, -0.00096577], [-0.00112673, -0.00112673, -0.00096577]]
      - add
    body.wrist_3_link|inertial.diaginertia:
      - [[-6.23071971e-05, -4.67237018e-05, -4.67237018e-05], [-6.23071971e-05, -4.67237018e-05, -4.67237018e-05]]
      - add

  joint_stiffness:
    # Joint stiffness
    joint.shoulder_pan_joint|stiffness:
      - [0.03024275, 0.03024275]
      - add
    joint.shoulder_lift_joint|stiffness:
      - [0.00107434, 0.00107434]
      - add
    joint.elbow_joint|stiffness:
      - [0.07393755, 0.07393755]
      - add
    joint.wrist_1_joint|stiffness:
      - [0.06627656, 0.06627656]
      - add
    joint.wrist_2_joint|stiffness:
      - [0.01816769, 0.01816769]
      - add
    joint.wrist_3_joint|stiffness:
      - [0.03330833, 0.03330833]
      - add

  gravity:
    # Gravity
    gravity:
      - [-0.2745999999999995, -0.2745999999999995]
      - add

  robot_color:
    material.black|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set
    material.jointgray|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set
    material.linkgray|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set
    material.urblue|rgba:
      - [[0.0, 0.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
      - set