name: pick_cube
dataset_dir: "/home/ahmed/Desktop/workspace/ml_sim_env/dataset_for_training/pick_cube/clean"
num_episodes: 800
episode_len: 165
state_dim: 7
action_dim: 8
camera_names: ['top_cam', 'hand_eye_cam']