name: pick_cube
real_dataset_dir: "/workspace/tao-experiments/database/real_data" ## ur5e_real_nov25
dataset_dir: "/workspace/tao_experiments/database/pick_cube" ## ur5e_real_nov11_150
failure_dataset_dir: "/workspace/tao_experiments/database/failure_data" ## dataset_failure_gt
num_episodes: 200
episode_len: 165
state_dim: 7
action_dim: 8
camera_names: ["top_cam", "hand_eye_cam"]
fine_tune: True
