seed: 0
ckpt_path: '/home/ahmed/Desktop/workspace/ml_sim_env/logs/241101_204958/pick_cube/All/policy_best_epoch_13712_seed_0.ckpt'
temporal_agg: False
is_render: True
rollout_num: 10

defaults:
  - task_config: pick_cube
  - policy_config: policy_default