seed: 0
batch_size: 2
num_epochs: 10000
eval_interval: 500
ckpt_save_interval: 5000
ckpt_save_list: [10, 100, 500, 1000, 3000, 5000, 10000]
rollout_num: 10
ckpt_path: "/workspace/tao_experiments/database/base_model/checkpoint/policy_epoch_100000_seed_54.ckpt"

defaults:
  - task_config: pick_cube
  - policy_config: policy_default
