seed: 0
batch_size: 32
num_epochs: 10000
eval_interval: 500
ckpt_save_interval: 5000
ckpt_save_list: [10, 100, 500, 1000, 5000, 10000]
rollout_num: 10
ckpt_path: '/home/ahmed/Desktop/workspace/ml_sim_env/pretrained_ckpt/policy_epoch_100000_seed_54.ckpt'

defaults:
  - task_config: pick_cube
  - policy_config: policy_default